config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#home'
  resources :posts,          only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_category_relations
  has_many :categories, through: :post_category_relations
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }
  validates :name, length: { maximum: 50 }
  validates :text, length: { maximum: 1000 }

  def self.search(search)
    if search
      Post.joins(:comments).includes(:comments).where(['comments.content LIKE ?', "%#{search}%"])
      .or(Post.joins(:comments).includes(:comments).where(['posts.content LIKE ?', "%#{search}%"]))
      .or(Post.joins(:comments).includes(:comments).where(['posts.text LIKE ?', "%#{search}%"]))
    else
      all
    end
  end
end

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "5channel", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :名前 %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :スレッドタイトル %><br />
    <%= f.text_area :content, size: "100", placeholder: "新しいスレッドのタイトル" %>
  </div>
  <p>
    <%= f.label :category, 'カテゴリ（複数選択可）' %><br>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
      <%= category.label do %>
        <%= category.check_box %>
        <%= category.text %>
      <% end %>
    <% end %>
  </p>
  <div class="field">
    <%= f.label :内容 %><br />
    <%= f.text_area :text, autofocus: true, autocomplete: "text", class: 'form-control' %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/shared/_search_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "5channel", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="hh-search">
          <%= form_tag(root_path, :method => 'get') do %>
            <%= text_field_tag :search, "キーワードを入力", {class: "search-form", id: "search-text"} %>
            <%= submit_tag '検索', :name => nil, class: "btn btn-primary search-btn" %>
          <% end %>
        </li>
        <li><%= link_to "Home",   root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>