config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#home'
  resources :posts,          only: [:show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_category_relations
  has_many :categories, through: :post_category_relations
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }
  validates :name, length: { maximum: 50 }
  validates :text, length: { maximum: 1000 }

  def self.search(search)
    if search
      Post.joins(:comments).includes(:comments).where(['comments.content LIKE ?', "%#{search}%"])
      .or(Post.joins(:comments).includes(:comments).where(['posts.content LIKE ?', "%#{search}%"]))
      .or(Post.joins(:comments).includes(:comments).where(['posts.text LIKE ?', "%#{search}%"]))
    else
      all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    # @comments = @post.comments
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_url
    else
      redirect_to root_url
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_url
  end
  
  private

    def post_params
      params.require(:post).permit(:content, :name, :email, :text, category_ids: [])
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/posts/_post.html.erb
<li class="hp" id="post-<%= post.id %>">
  <%= link_to post do %>
    <h3 class="content"><%= post.content %></h3>
  <% end %>
  <p class="hp-info">
    <span class="hp-name"><%= post.name %></span>
    <%= time_ago_in_words(post.created_at) %> ago.
  </p>
  <span>【カテゴリ】</span>
  <% post.categories.each do |category| %>
    <%= category.name %>
  <% end %>
  <% if current_user?(post.user) %>
    [<%= link_to "edit", edit_post_path(post.id) %>]
    [<%= link_to "delete", post, method: :delete,
                                     data: { confirm: "You sure?" } %>]
  <% end %>
  <h3 class="hp-text"><%= post.text %></h3>
  <div class="hp-res">
    <ol>
      <% post.comments.first(5).each do |c| %>
        <li>
          <%= c.name %> <%= time_ago_in_words(c.created_at) %> ago.
          <br />
          <%= c.content %>
        </li>
        <br />
      <% end %>
      <%= link_to post do %>
        <% if post.comments.length >= 6 %>
          <p>・</p>
          <p>・</p>
          <p>・</p>
        <% end %>
      <% end %>
    </ol>
  </div>
</li>

app/views/posts/edit.html.erb
<%= render 'shared/header' %>
<h2>スレッドを編集する</h2>
<%= render 'shared/post_form' %>

app/views/posts/show.html.erb
<%= render 'shared/header' %>
<div id="post-<%= @post.id %>">
  <div class="ps-thread">
    <h3 class="ps-content"><%= @post.content %></h3>
    <div class="ps-category">
      <span>【カテゴリ】</span>
      <% @post.categories.each do |category| %>
        <%= category.name %>
      <% end %>
      <span class="ps-timestamp">
        <%= time_ago_in_words(@post.created_at) %> ago.
      </span>
    </div>
    <p class="hp-text"><%= @post.text %></p>
  </div>
  <div class="comment-wrapper border-top">
    <div class="res">
      <h4><%= @post.content %></h4>
      <ol>
        <% @post.comments.each do |c| %>
          <li>
            <%= c.name %> <%= time_ago_in_words(c.created_at) %> ago.
            <% if c.user == current_user %>
              <%= link_to "[削除]",[@post,c], method: :delete if @post %>
            <% end %>
            <br />
            <%= c.content %>
          </li>
          <br />
        <% end %>
      </ol>
    </div>
    <div class="ps-form">
      <%= form_for [@post, @comment] do |f| %>
        <h4 class="ps-write">書き込み欄</h4>
        <div class="field">
          <%= f.label :名前 %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
        </div>
        <div class="ps-text">
          <%= f.text_area :content, size:"100×100", class: 'form-control', placeholder: "書き込み欄\n(1000字以内)" %>
        </div>
        <%= f.submit "書き込む", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>